config/routes.rb
Rails.application.routes.draw do
  resources :searches, only: [:show, :new, :create]
  resources :artists, only: [:new, :create]
  root to: 'artists#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  include Rspotify

  before_action :authenticate_rspotify, only: :create

  def new
    @searched = format_searched(session.fetch(:searched, []))
  end

  def create
    @image = show_artists
    respond_to do |format|
      if @image
        session[:artist_image_url] = @image
        format.html { redirect_to controller: :searches, action: :new }
      end
    end
  end

  private

  def format_searched(searched)
    formatted_searched = []
    searched.each do |id|
      search = Search.find(id)
      formatted_searched << search
    end
    formatted_searched
  end

  def show_artists
    artist = find_artist_by_name(params[:artist])
    session[:artist_id] = artist.id
    session[:artist] = artist.name
    get_image_url(artist.images)
  end
end

app/controllers/concerns/rspotify.rb
module Rspotify
  extend ActiveSupport::Concern

  private

  def authenticate_rspotify
    rspotify_client = Rails.application.config.spotify_credentials[:rspotify_client]
    rspotify_secret = Rails.application.config.spotify_credentials[:rspotify_secret]
    RSpotify::authenticate(rspotify_client, rspotify_secret)
  end

  def find_artist_by_id(artist_id)
    RSpotify::Artist.find(artist_id)
  end

  def find_artist_by_name(query)
    RSpotify::Artist.search(query).first
  end

  def find_album_by_id(album_id)
    RSpotify::Album.find(album_id)
  end

  def get_image_url(images)
    # The Spotify images array is of various sizes but starts with widest. We
    # are selecting the image closest yet smaller than a width of 320
    ideal_images = images.select { |image| image['width'] <= 320 }
    ideal_image = ideal_images.first || images.second
    ideal_image['url']
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  include Rspotify

  before_action :authenticate_rspotify, only: :new
  before_action :set_search, only: :show

  def new
    @search = Search.new
    @image = session[:artist_image_url]
    @albums = all_albums
  end

  def create
    @search = create_search

    respond_to do |format|
      if @search.save
        save_search_to_sessions(@search.id)
        format.html { redirect_to @search }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @search = Search.find(params[:id])
  end

  private

  def all_albums
    artist = find_artist_by_id(session[:artist_id])
    format_albums(artist.albums(limit: 15, market: 'US'))
  end

  def format_albums(albums)
    formatted_albums = []
    albums.each do |album|
      formatted_album = {
        :album_id => album.id,
        :album_name => album.name
      }
      formatted_albums << formatted_album
    end
    formatted_albums.uniq { |formatted_album| formatted_album[:album_name] }
  end

  def set_search
    @search = Search.find(params[:id])
  end

  def create_search
    search = Search.new(search_params)
    search.artist_id = session[:artist_id]
    search.artist = session[:artist]

    album = find_album_by_id(search.album_id)
    search.album = album.name
    search.image = get_image_url(album.images)
    search.score = calculate_score(album)
    search
  end

  def search_params
    params.require(:search).permit(:album_id)
  end

  def save_search_to_sessions(search_id)
    searched = session.fetch(:searched, [])
    searched.unshift(search_id)
    session[:searched] = searched
  end

  def calculate_score(album)
    tracks = album.tracks
    mean = album_mean_popularity(tracks)
    standard_deviation = calculate_standard_deviation(tracks, mean)
    score = normalize_score(standard_deviation)
    format_score(score)
  end

  def album_mean_popularity(tracks)
    total_popularity = 0
    tracks.each do |track|
      total_popularity += track.popularity
    end
    total_popularity / tracks.length
  end

  def calculate_standard_deviation(tracks, mean)
    total = 0
    tracks.each do |track|
      difference = track.popularity - mean
      total += difference**2
    end
    Math.sqrt(total / tracks.length)
  end

  def normalize_score(standard_deviation)
    standard_deviation * 2
  end

  def format_score(score)
    score = 100 - score
    score.round(2)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/artists/_artist_form.html.erb
<%= form_with method: :post, url: artists_path, class: "form-group mb-3" do |form| %>

  <div class="field form-group col-md-4 col-md-offset-4">
    <%= form.text_field :artist, id: "artist-field", class: "form-control justify-content-center", 
    placeholder: "Artist", autocomplete: "off", onkeyup: "queryChange(this.value)" %>
  </div>

  <div class="actions col-md-1 col-centered">
    <%= form.submit "Search", id: "search-artist-button", class: "btn btn-success btn-lg", disabled: true %>
  </div>
<% end %>

<% content_for :javascript do %>
  <script type="text/javascript">
    function queryChange(query) {
      $('#search-artist-button').prop('disabled', query.length == 0);
    }
  </script>
<% end %>

app/views/artists/_form.html.erb
<%= form_with method: :post, url: artists_path, class: "form-group mb-3" do |form| %>

  <div class="field form-group col-md-4 col-md-offset-4">
    <%= form.text_field :artist, id: "artist-field", class: "form-control justify-content-center", 
    placeholder: "Artist", autocomplete: "off", onkeyup: "queryChange(this.value)" %>
  </div>

  <div class="actions col-md-1 col-centered">
    <%= form.submit "Search", id: "search-artist-button", class: "btn btn-success btn-lg", disabled: true %>
  </div>
<% end %>

<% content_for :javascript do %>
  <script type="text/javascript">
    function queryChange(query) {
      $('#search-artist-button').prop('disabled', query.length == 0);
    }
  </script>
<% end %>

app/views/artists/new.html.erb
<%= stylesheet_link_tag "artists", media: "all", "data-turbolinks-track" => true %>
<%= render 'artist_form', artist: @artist %>
<div class="page-results">
  <% @searched.each do |search| %>
    <%= link_to search_path(:id => search.id) do %>
        <% image_tag search.image, width: 320, height: 320, border: 0 %>
    <% end %>
    <p class="text-white new-score">
      <strong>Score: </strong><%= search.score %>
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Throughput</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="all">
    <div class="container home">
      <h1 class="main-title">Throughput</h1>
        <%= yield %>
        <%= yield :javascript %>
    </div>
  </body>
</html>

app/views/searches/_search_form.html.erb
<%= form_with model: @search, class: "form-group" do |form| %>
  <div class="actions col-md-1 col-centered">
    <div class="dropdown btn-group">
      <button class="btn btn-success btn-lg dropdown-toggle" data-toggle="dropdown" type="button">
        Albums <span class="caret">
      </button>
      <ul class="dropdown-menu">
        <% @albums.each do |album| %>
          <li><%= link_to album[:album_name], searches_path(:search => album), method: :post %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/new.html.erb
<div class="album-image">
    <img src=<%= @image %> class="artist-image" />
</div>
<%= render 'search_form', search: @search %>

app/views/searches/show.html.erb
<div class="page-results">
  <div class="album-image">
    <img src=<%= @search.image %> />
  </div>

  <p class="text-white">
    <strong>Artist: </strong> <%= @search.artist %>
  </p>

  <p class="text-white">
    <strong>Album: </strong><%= @search.album %>
  </p>

  <p class="text-white">
    <strong>Score: </strong><%= @search.score %>
  </p>

  <div class="btn btn-success">
    <%= link_to 'Another Search', root_path, :class => "btn search btn-lg" %>
  </div>
</div>